@startuml

skinparam componentStyle uml2

:Letztverbraucher:
node "Smart Meter Gateway" as Smgw
node "Zähler 1" as Meter1
node "Zähler n" as Meter2

:Lieferant: as Lieferant
file "Lieferanten-XML-Datei" as LieferantenXml

frame TRuDI {
}

Letztverbraucher --> TRuDI
TRuDI --> Smgw

Lieferant --> LieferantenXml 
LieferantenXml --> TRuDI
Smgw --> Meter1
Smgw --> Meter2

@enduml

